---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dasdns.io/watch: "true"
  labels:
    app: frontend
  name: frontend-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: frontend

