apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2025-12-21T12:01:51Z"
  generation: 1
  name: mutating-webhook-configuration
  resourceVersion: "1097104"
  uid: cc10bb1d-5a93-4b63-8214-258054ea47c6
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-deployment
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mdeployment-v1.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dns-dnspolicies-io-v1alpha1-dnspolicy
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mdnspolicy-v1alpha1.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - dns.dnspolicies.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnspolicies
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
