webhook:
  image: docker.io/emirozbir/dashdns-webhook
  pullPolicy: Always
  tag: "latest"
  dns_service:
    name: dashdns-svc
    namespace: "dashdns"
  certChain:
    ca: ""
    cert: ""
    key: ""

controller:
  replicaCount: 1

  image:
    repository: docker.io/emirozbir/dns-mesh-controller
    pullPolicy: IfNotPresent
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}
  service:
    type: ClusterIP
    port: 8443
    apiPort: 5959

  kubeDns:
    namespace: kube-system
    secretName: kube-dns-tls

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}