name: dns-mesh-controller-acceptance-tests

on:
  push:
    tags:
      - "*"

jobs:
  test-entire-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Setup Test Suite & Apply
        id: build_img
        run: |
          #!/bin/bash
          ./setup-test-suite.sh $IMAGE_TO_BUILD
        env:
          IMAGE_TO_BUILD: "${{ env.TAG }}"