name: dns-mesh-controller-functional-tests

on:
  push:
    tags:
      - "*"
    branches:
      - "main"
      - "fix-test-suite"

jobs:
  test-entire-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Setup Test Suite & Apply
        id: build_img
        run: |
          #!/bin/bash
          ./setup-test-suite.sh v2.0.0-rc
        env:
          IMAGE_TO_BUILD: "${{ env.TAG }}"